"""add suggestion column to mood_logs

Revision ID: 24b24d12c2eb
Revises: 90a03fdad3d7
Create Date: 2025-05-28 09:59:23.920172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b24d12c2eb'
down_revision: Union[str, None] = '90a03fdad3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
